################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/dietlibc-0.34/lib/__alarm.c \
../src/dietlibc-0.34/lib/__dtostr.c \
../src/dietlibc-0.34/lib/__fcntl64.c \
../src/dietlibc-0.34/lib/__finite.c \
../src/dietlibc-0.34/lib/__fstat64.c \
../src/dietlibc-0.34/lib/__fstatat64.c \
../src/dietlibc-0.34/lib/__fstatfs64.c \
../src/dietlibc-0.34/lib/__ftruncate64.c \
../src/dietlibc-0.34/lib/__get_cur_tcb.c \
../src/dietlibc-0.34/lib/__getcwd.c \
../src/dietlibc-0.34/lib/__inotify_init.c \
../src/dietlibc-0.34/lib/__isinf.c \
../src/dietlibc-0.34/lib/__isnan.c \
../src/dietlibc-0.34/lib/__lstat64.c \
../src/dietlibc-0.34/lib/__ltostr.c \
../src/dietlibc-0.34/lib/__mmap.c \
../src/dietlibc-0.34/lib/__ptrace.c \
../src/dietlibc-0.34/lib/__sched_getaffinity.c \
../src/dietlibc-0.34/lib/__sendfile64.c \
../src/dietlibc-0.34/lib/__stat64.c \
../src/dietlibc-0.34/lib/__stat64_cvt.c \
../src/dietlibc-0.34/lib/__statfs64.c \
../src/dietlibc-0.34/lib/__stime.c \
../src/dietlibc-0.34/lib/__sysctl.c \
../src/dietlibc-0.34/lib/__time.c \
../src/dietlibc-0.34/lib/__truncate64.c \
../src/dietlibc-0.34/lib/__umount.c \
../src/dietlibc-0.34/lib/__utime.c \
../src/dietlibc-0.34/lib/__v_printf.c \
../src/dietlibc-0.34/lib/__v_scanf.c \
../src/dietlibc-0.34/lib/_brk.c \
../src/dietlibc-0.34/lib/_getpriority.c \
../src/dietlibc-0.34/lib/abort.c \
../src/dietlibc-0.34/lib/abs.c \
../src/dietlibc-0.34/lib/accept.c \
../src/dietlibc-0.34/lib/adjtime.c \
../src/dietlibc-0.34/lib/alloc.c \
../src/dietlibc-0.34/lib/arc4random.c \
../src/dietlibc-0.34/lib/assert_fail.c \
../src/dietlibc-0.34/lib/atexit.c \
../src/dietlibc-0.34/lib/atof.c \
../src/dietlibc-0.34/lib/atoi.c \
../src/dietlibc-0.34/lib/atol.c \
../src/dietlibc-0.34/lib/atoll.c \
../src/dietlibc-0.34/lib/bind.c \
../src/dietlibc-0.34/lib/binshstr.c \
../src/dietlibc-0.34/lib/bsearch.c \
../src/dietlibc-0.34/lib/btowc.c \
../src/dietlibc-0.34/lib/call_once.c \
../src/dietlibc-0.34/lib/cfgetospeed.c \
../src/dietlibc-0.34/lib/cfmakeraw.c \
../src/dietlibc-0.34/lib/cfsetispeed.c \
../src/dietlibc-0.34/lib/cfsetospeed.c \
../src/dietlibc-0.34/lib/closedir.c \
../src/dietlibc-0.34/lib/cnd_broadcast.c \
../src/dietlibc-0.34/lib/cnd_destroy.c \
../src/dietlibc-0.34/lib/cnd_init.c \
../src/dietlibc-0.34/lib/cnd_signal.c \
../src/dietlibc-0.34/lib/cnd_timedwait.c \
../src/dietlibc-0.34/lib/cnd_wait.c \
../src/dietlibc-0.34/lib/connect.c \
../src/dietlibc-0.34/lib/creat.c \
../src/dietlibc-0.34/lib/creat64.c \
../src/dietlibc-0.34/lib/div.c \
../src/dietlibc-0.34/lib/errlistu.c \
../src/dietlibc-0.34/lib/errno.c \
../src/dietlibc-0.34/lib/errno_location.c \
../src/dietlibc-0.34/lib/eventfd.c \
../src/dietlibc-0.34/lib/exec_lib.c \
../src/dietlibc-0.34/lib/execl.c \
../src/dietlibc-0.34/lib/execle.c \
../src/dietlibc-0.34/lib/execlp.c \
../src/dietlibc-0.34/lib/execv.c \
../src/dietlibc-0.34/lib/execvp.c \
../src/dietlibc-0.34/lib/explicit_bzero.c \
../src/dietlibc-0.34/lib/fdopendir.c \
../src/dietlibc-0.34/lib/ffs.c \
../src/dietlibc-0.34/lib/fstatvfs.c \
../src/dietlibc-0.34/lib/ftw.c \
../src/dietlibc-0.34/lib/ftw64.c \
../src/dietlibc-0.34/lib/getdomainname.c \
../src/dietlibc-0.34/lib/getentropy.c \
../src/dietlibc-0.34/lib/getenv.c \
../src/dietlibc-0.34/lib/gethostname.c \
../src/dietlibc-0.34/lib/getopt.c \
../src/dietlibc-0.34/lib/getpeername.c \
../src/dietlibc-0.34/lib/getpgrp.c \
../src/dietlibc-0.34/lib/getsockname.c \
../src/dietlibc-0.34/lib/getsockopt.c \
../src/dietlibc-0.34/lib/hcreate.c \
../src/dietlibc-0.34/lib/hcreate_r.c \
../src/dietlibc-0.34/lib/hdestroy_r.c \
../src/dietlibc-0.34/lib/hsearch_r.c \
../src/dietlibc-0.34/lib/htonl.c \
../src/dietlibc-0.34/lib/htons.c \
../src/dietlibc-0.34/lib/if_freenameindex.c \
../src/dietlibc-0.34/lib/if_indextoname.c \
../src/dietlibc-0.34/lib/if_nameindex.c \
../src/dietlibc-0.34/lib/if_nametoindex.c \
../src/dietlibc-0.34/lib/ipv6constants.c \
../src/dietlibc-0.34/lib/isalnum.c \
../src/dietlibc-0.34/lib/isalpha.c \
../src/dietlibc-0.34/lib/isascii.c \
../src/dietlibc-0.34/lib/isatty.c \
../src/dietlibc-0.34/lib/isblank.c \
../src/dietlibc-0.34/lib/iscntrl.c \
../src/dietlibc-0.34/lib/isdigit.c \
../src/dietlibc-0.34/lib/isgraph.c \
../src/dietlibc-0.34/lib/islower.c \
../src/dietlibc-0.34/lib/isprint.c \
../src/dietlibc-0.34/lib/ispunct.c \
../src/dietlibc-0.34/lib/isspace.c \
../src/dietlibc-0.34/lib/isupper.c \
../src/dietlibc-0.34/lib/iswalnum.c \
../src/dietlibc-0.34/lib/iswalpha.c \
../src/dietlibc-0.34/lib/iswblank.c \
../src/dietlibc-0.34/lib/iswcntrl.c \
../src/dietlibc-0.34/lib/iswdigit.c \
../src/dietlibc-0.34/lib/iswgraph.c \
../src/dietlibc-0.34/lib/iswlower.c \
../src/dietlibc-0.34/lib/iswprint.c \
../src/dietlibc-0.34/lib/iswpunct.c \
../src/dietlibc-0.34/lib/iswspace.c \
../src/dietlibc-0.34/lib/iswupper.c \
../src/dietlibc-0.34/lib/iswxdigit.c \
../src/dietlibc-0.34/lib/isxdigit.c \
../src/dietlibc-0.34/lib/labs.c \
../src/dietlibc-0.34/lib/lc_ctype.c \
../src/dietlibc-0.34/lib/ldiv.c \
../src/dietlibc-0.34/lib/listen.c \
../src/dietlibc-0.34/lib/llabs.c \
../src/dietlibc-0.34/lib/lldiv.c \
../src/dietlibc-0.34/lib/lockf.c \
../src/dietlibc-0.34/lib/longjmp.c \
../src/dietlibc-0.34/lib/lseek64.c \
../src/dietlibc-0.34/lib/makecontext.c \
../src/dietlibc-0.34/lib/mblen.c \
../src/dietlibc-0.34/lib/mbrlen.c \
../src/dietlibc-0.34/lib/mbrtowc.c \
../src/dietlibc-0.34/lib/mbsinit.c \
../src/dietlibc-0.34/lib/mbsrtowcs.c \
../src/dietlibc-0.34/lib/mbstowcs.c \
../src/dietlibc-0.34/lib/mbtowc.c \
../src/dietlibc-0.34/lib/memccpy.c \
../src/dietlibc-0.34/lib/memchr.c \
../src/dietlibc-0.34/lib/memcmp.c \
../src/dietlibc-0.34/lib/memcpy.c \
../src/dietlibc-0.34/lib/memmem.c \
../src/dietlibc-0.34/lib/memmove.c \
../src/dietlibc-0.34/lib/memrchr.c \
../src/dietlibc-0.34/lib/memset.c \
../src/dietlibc-0.34/lib/mkfifo.c \
../src/dietlibc-0.34/lib/mmap64.c \
../src/dietlibc-0.34/lib/mq_getattr.c \
../src/dietlibc-0.34/lib/mq_receive.c \
../src/dietlibc-0.34/lib/mq_send.c \
../src/dietlibc-0.34/lib/msgctl.c \
../src/dietlibc-0.34/lib/msgget.c \
../src/dietlibc-0.34/lib/msgrcv.c \
../src/dietlibc-0.34/lib/msgsnd.c \
../src/dietlibc-0.34/lib/mtx_destroy.c \
../src/dietlibc-0.34/lib/mtx_init.c \
../src/dietlibc-0.34/lib/mtx_lock.c \
../src/dietlibc-0.34/lib/mtx_timedlock.c \
../src/dietlibc-0.34/lib/mtx_trylock.c \
../src/dietlibc-0.34/lib/mtx_unlock.c \
../src/dietlibc-0.34/lib/nice.c \
../src/dietlibc-0.34/lib/open64.c \
../src/dietlibc-0.34/lib/opendir.c \
../src/dietlibc-0.34/lib/perror.c \
../src/dietlibc-0.34/lib/posix_fallocate.c \
../src/dietlibc-0.34/lib/pread.c \
../src/dietlibc-0.34/lib/pselect.c \
../src/dietlibc-0.34/lib/putenv.c \
../src/dietlibc-0.34/lib/pwrite.c \
../src/dietlibc-0.34/lib/qsort.c \
../src/dietlibc-0.34/lib/raise.c \
../src/dietlibc-0.34/lib/rand.c \
../src/dietlibc-0.34/lib/rand48.c \
../src/dietlibc-0.34/lib/rand_r.c \
../src/dietlibc-0.34/lib/readdir.c \
../src/dietlibc-0.34/lib/readdir64.c \
../src/dietlibc-0.34/lib/readdir_r.c \
../src/dietlibc-0.34/lib/reallocarray.c \
../src/dietlibc-0.34/lib/reboot.c \
../src/dietlibc-0.34/lib/recv.c \
../src/dietlibc-0.34/lib/recvfrom.c \
../src/dietlibc-0.34/lib/recvmsg.c \
../src/dietlibc-0.34/lib/remove.c \
../src/dietlibc-0.34/lib/rewind.c \
../src/dietlibc-0.34/lib/rewinddir.c \
../src/dietlibc-0.34/lib/sbrk.c \
../src/dietlibc-0.34/lib/secure_getenv.c \
../src/dietlibc-0.34/lib/seekdir.c \
../src/dietlibc-0.34/lib/semctl.c \
../src/dietlibc-0.34/lib/semget.c \
../src/dietlibc-0.34/lib/semop.c \
../src/dietlibc-0.34/lib/send.c \
../src/dietlibc-0.34/lib/sendmsg.c \
../src/dietlibc-0.34/lib/sendto.c \
../src/dietlibc-0.34/lib/setlinebuf.c \
../src/dietlibc-0.34/lib/setpgrp.c \
../src/dietlibc-0.34/lib/setsockopt.c \
../src/dietlibc-0.34/lib/shmat.c \
../src/dietlibc-0.34/lib/shmctl.c \
../src/dietlibc-0.34/lib/shmdt.c \
../src/dietlibc-0.34/lib/shmget.c \
../src/dietlibc-0.34/lib/shutdown.c \
../src/dietlibc-0.34/lib/sigaction.c \
../src/dietlibc-0.34/lib/sigaddset.c \
../src/dietlibc-0.34/lib/sigandset.c \
../src/dietlibc-0.34/lib/sigdelset.c \
../src/dietlibc-0.34/lib/sigemptyset.c \
../src/dietlibc-0.34/lib/sigfillset.c \
../src/dietlibc-0.34/lib/siginterrupt.c \
../src/dietlibc-0.34/lib/sigisemptyset.c \
../src/dietlibc-0.34/lib/sigismember.c \
../src/dietlibc-0.34/lib/sigjmp.c \
../src/dietlibc-0.34/lib/signal.c \
../src/dietlibc-0.34/lib/signalfd.c \
../src/dietlibc-0.34/lib/sigorset.c \
../src/dietlibc-0.34/lib/sigpending.c \
../src/dietlibc-0.34/lib/sigprocmask.c \
../src/dietlibc-0.34/lib/sigqueueinfo.c \
../src/dietlibc-0.34/lib/sigsuspend.c \
../src/dietlibc-0.34/lib/sigtimedwait.c \
../src/dietlibc-0.34/lib/sigwait.c \
../src/dietlibc-0.34/lib/siphash24.c \
../src/dietlibc-0.34/lib/sleep.c \
../src/dietlibc-0.34/lib/snprintf.c \
../src/dietlibc-0.34/lib/socket.c \
../src/dietlibc-0.34/lib/socketpair.c \
../src/dietlibc-0.34/lib/sprintf.c \
../src/dietlibc-0.34/lib/sscanf.c \
../src/dietlibc-0.34/lib/stack_smash_handler.c \
../src/dietlibc-0.34/lib/stack_smash_handler2.c \
../src/dietlibc-0.34/lib/stack_smash_handler3.c \
../src/dietlibc-0.34/lib/statfs64_cvt.c \
../src/dietlibc-0.34/lib/statvfs.c \
../src/dietlibc-0.34/lib/statvfs_cvt.c \
../src/dietlibc-0.34/lib/stpcpy.c \
../src/dietlibc-0.34/lib/stpncpy.c \
../src/dietlibc-0.34/lib/strcasecmp.c \
../src/dietlibc-0.34/lib/strcat.c \
../src/dietlibc-0.34/lib/strchr.c \
../src/dietlibc-0.34/lib/strcmp.c \
../src/dietlibc-0.34/lib/strcpy.c \
../src/dietlibc-0.34/lib/strcspn.c \
../src/dietlibc-0.34/lib/strdup.c \
../src/dietlibc-0.34/lib/strerror.c \
../src/dietlibc-0.34/lib/strlcat.c \
../src/dietlibc-0.34/lib/strlcpy.c \
../src/dietlibc-0.34/lib/strlen.c \
../src/dietlibc-0.34/lib/strncasecmp.c \
../src/dietlibc-0.34/lib/strncat.c \
../src/dietlibc-0.34/lib/strncmp.c \
../src/dietlibc-0.34/lib/strncpy.c \
../src/dietlibc-0.34/lib/strnlen.c \
../src/dietlibc-0.34/lib/strpbrk.c \
../src/dietlibc-0.34/lib/strrchr.c \
../src/dietlibc-0.34/lib/strsep.c \
../src/dietlibc-0.34/lib/strspn.c \
../src/dietlibc-0.34/lib/strstr.c \
../src/dietlibc-0.34/lib/strtod.c \
../src/dietlibc-0.34/lib/strtof.c \
../src/dietlibc-0.34/lib/strtok.c \
../src/dietlibc-0.34/lib/strtok_r.c \
../src/dietlibc-0.34/lib/strtol.c \
../src/dietlibc-0.34/lib/strtold.c \
../src/dietlibc-0.34/lib/strtoll.c \
../src/dietlibc-0.34/lib/strtoul.c \
../src/dietlibc-0.34/lib/strtoull.c \
../src/dietlibc-0.34/lib/strverscmp.c \
../src/dietlibc-0.34/lib/strxfrm.c \
../src/dietlibc-0.34/lib/swab.c \
../src/dietlibc-0.34/lib/swapcontext.c \
../src/dietlibc-0.34/lib/sys_siglist.c \
../src/dietlibc-0.34/lib/tcdrain.c \
../src/dietlibc-0.34/lib/tcflow.c \
../src/dietlibc-0.34/lib/tcflush.c \
../src/dietlibc-0.34/lib/tcgetattr.c \
../src/dietlibc-0.34/lib/tcgetpgrp.c \
../src/dietlibc-0.34/lib/tcgetsid.c \
../src/dietlibc-0.34/lib/tcsendbreak.c \
../src/dietlibc-0.34/lib/tcsetattr.c \
../src/dietlibc-0.34/lib/tcsetpgrp.c \
../src/dietlibc-0.34/lib/telldir.c \
../src/dietlibc-0.34/lib/thrd_create.c \
../src/dietlibc-0.34/lib/thrd_current.c \
../src/dietlibc-0.34/lib/thrd_detach.c \
../src/dietlibc-0.34/lib/thrd_exit.c \
../src/dietlibc-0.34/lib/thrd_join.c \
../src/dietlibc-0.34/lib/thrd_root.c \
../src/dietlibc-0.34/lib/timerfd_create.c \
../src/dietlibc-0.34/lib/timingsafe_bcmp.c \
../src/dietlibc-0.34/lib/timingsafe_memcmp.c \
../src/dietlibc-0.34/lib/tolower.c \
../src/dietlibc-0.34/lib/toupper.c \
../src/dietlibc-0.34/lib/towlower.c \
../src/dietlibc-0.34/lib/towupper.c \
../src/dietlibc-0.34/lib/tss_create.c \
../src/dietlibc-0.34/lib/tss_delete.c \
../src/dietlibc-0.34/lib/tss_get.c \
../src/dietlibc-0.34/lib/tss_set.c \
../src/dietlibc-0.34/lib/ttyname.c \
../src/dietlibc-0.34/lib/usleep.c \
../src/dietlibc-0.34/lib/vdso_dlsym.c \
../src/dietlibc-0.34/lib/vfork.c \
../src/dietlibc-0.34/lib/vsnprintf.c \
../src/dietlibc-0.34/lib/vsprintf.c \
../src/dietlibc-0.34/lib/vsscanf.c \
../src/dietlibc-0.34/lib/wait.c \
../src/dietlibc-0.34/lib/wait3.c \
../src/dietlibc-0.34/lib/wcrtomb.c \
../src/dietlibc-0.34/lib/wcscat.c \
../src/dietlibc-0.34/lib/wcschr.c \
../src/dietlibc-0.34/lib/wcscmp.c \
../src/dietlibc-0.34/lib/wcscpy.c \
../src/dietlibc-0.34/lib/wcslen.c \
../src/dietlibc-0.34/lib/wcsncat.c \
../src/dietlibc-0.34/lib/wcsncmp.c \
../src/dietlibc-0.34/lib/wcsncpy.c \
../src/dietlibc-0.34/lib/wcsrchr.c \
../src/dietlibc-0.34/lib/wcsrtombs.c \
../src/dietlibc-0.34/lib/wcsstr.c \
../src/dietlibc-0.34/lib/wcstombs.c \
../src/dietlibc-0.34/lib/wcswidth.c \
../src/dietlibc-0.34/lib/wctomb.c \
../src/dietlibc-0.34/lib/wcwidth.c \
../src/dietlibc-0.34/lib/write12.c 

OBJS += \
./src/dietlibc-0.34/lib/__alarm.o \
./src/dietlibc-0.34/lib/__dtostr.o \
./src/dietlibc-0.34/lib/__fcntl64.o \
./src/dietlibc-0.34/lib/__finite.o \
./src/dietlibc-0.34/lib/__fstat64.o \
./src/dietlibc-0.34/lib/__fstatat64.o \
./src/dietlibc-0.34/lib/__fstatfs64.o \
./src/dietlibc-0.34/lib/__ftruncate64.o \
./src/dietlibc-0.34/lib/__get_cur_tcb.o \
./src/dietlibc-0.34/lib/__getcwd.o \
./src/dietlibc-0.34/lib/__inotify_init.o \
./src/dietlibc-0.34/lib/__isinf.o \
./src/dietlibc-0.34/lib/__isnan.o \
./src/dietlibc-0.34/lib/__lstat64.o \
./src/dietlibc-0.34/lib/__ltostr.o \
./src/dietlibc-0.34/lib/__mmap.o \
./src/dietlibc-0.34/lib/__ptrace.o \
./src/dietlibc-0.34/lib/__sched_getaffinity.o \
./src/dietlibc-0.34/lib/__sendfile64.o \
./src/dietlibc-0.34/lib/__stat64.o \
./src/dietlibc-0.34/lib/__stat64_cvt.o \
./src/dietlibc-0.34/lib/__statfs64.o \
./src/dietlibc-0.34/lib/__stime.o \
./src/dietlibc-0.34/lib/__sysctl.o \
./src/dietlibc-0.34/lib/__time.o \
./src/dietlibc-0.34/lib/__truncate64.o \
./src/dietlibc-0.34/lib/__umount.o \
./src/dietlibc-0.34/lib/__utime.o \
./src/dietlibc-0.34/lib/__v_printf.o \
./src/dietlibc-0.34/lib/__v_scanf.o \
./src/dietlibc-0.34/lib/_brk.o \
./src/dietlibc-0.34/lib/_getpriority.o \
./src/dietlibc-0.34/lib/abort.o \
./src/dietlibc-0.34/lib/abs.o \
./src/dietlibc-0.34/lib/accept.o \
./src/dietlibc-0.34/lib/adjtime.o \
./src/dietlibc-0.34/lib/alloc.o \
./src/dietlibc-0.34/lib/arc4random.o \
./src/dietlibc-0.34/lib/assert_fail.o \
./src/dietlibc-0.34/lib/atexit.o \
./src/dietlibc-0.34/lib/atof.o \
./src/dietlibc-0.34/lib/atoi.o \
./src/dietlibc-0.34/lib/atol.o \
./src/dietlibc-0.34/lib/atoll.o \
./src/dietlibc-0.34/lib/bind.o \
./src/dietlibc-0.34/lib/binshstr.o \
./src/dietlibc-0.34/lib/bsearch.o \
./src/dietlibc-0.34/lib/btowc.o \
./src/dietlibc-0.34/lib/call_once.o \
./src/dietlibc-0.34/lib/cfgetospeed.o \
./src/dietlibc-0.34/lib/cfmakeraw.o \
./src/dietlibc-0.34/lib/cfsetispeed.o \
./src/dietlibc-0.34/lib/cfsetospeed.o \
./src/dietlibc-0.34/lib/closedir.o \
./src/dietlibc-0.34/lib/cnd_broadcast.o \
./src/dietlibc-0.34/lib/cnd_destroy.o \
./src/dietlibc-0.34/lib/cnd_init.o \
./src/dietlibc-0.34/lib/cnd_signal.o \
./src/dietlibc-0.34/lib/cnd_timedwait.o \
./src/dietlibc-0.34/lib/cnd_wait.o \
./src/dietlibc-0.34/lib/connect.o \
./src/dietlibc-0.34/lib/creat.o \
./src/dietlibc-0.34/lib/creat64.o \
./src/dietlibc-0.34/lib/div.o \
./src/dietlibc-0.34/lib/errlistu.o \
./src/dietlibc-0.34/lib/errno.o \
./src/dietlibc-0.34/lib/errno_location.o \
./src/dietlibc-0.34/lib/eventfd.o \
./src/dietlibc-0.34/lib/exec_lib.o \
./src/dietlibc-0.34/lib/execl.o \
./src/dietlibc-0.34/lib/execle.o \
./src/dietlibc-0.34/lib/execlp.o \
./src/dietlibc-0.34/lib/execv.o \
./src/dietlibc-0.34/lib/execvp.o \
./src/dietlibc-0.34/lib/explicit_bzero.o \
./src/dietlibc-0.34/lib/fdopendir.o \
./src/dietlibc-0.34/lib/ffs.o \
./src/dietlibc-0.34/lib/fstatvfs.o \
./src/dietlibc-0.34/lib/ftw.o \
./src/dietlibc-0.34/lib/ftw64.o \
./src/dietlibc-0.34/lib/getdomainname.o \
./src/dietlibc-0.34/lib/getentropy.o \
./src/dietlibc-0.34/lib/getenv.o \
./src/dietlibc-0.34/lib/gethostname.o \
./src/dietlibc-0.34/lib/getopt.o \
./src/dietlibc-0.34/lib/getpeername.o \
./src/dietlibc-0.34/lib/getpgrp.o \
./src/dietlibc-0.34/lib/getsockname.o \
./src/dietlibc-0.34/lib/getsockopt.o \
./src/dietlibc-0.34/lib/hcreate.o \
./src/dietlibc-0.34/lib/hcreate_r.o \
./src/dietlibc-0.34/lib/hdestroy_r.o \
./src/dietlibc-0.34/lib/hsearch_r.o \
./src/dietlibc-0.34/lib/htonl.o \
./src/dietlibc-0.34/lib/htons.o \
./src/dietlibc-0.34/lib/if_freenameindex.o \
./src/dietlibc-0.34/lib/if_indextoname.o \
./src/dietlibc-0.34/lib/if_nameindex.o \
./src/dietlibc-0.34/lib/if_nametoindex.o \
./src/dietlibc-0.34/lib/ipv6constants.o \
./src/dietlibc-0.34/lib/isalnum.o \
./src/dietlibc-0.34/lib/isalpha.o \
./src/dietlibc-0.34/lib/isascii.o \
./src/dietlibc-0.34/lib/isatty.o \
./src/dietlibc-0.34/lib/isblank.o \
./src/dietlibc-0.34/lib/iscntrl.o \
./src/dietlibc-0.34/lib/isdigit.o \
./src/dietlibc-0.34/lib/isgraph.o \
./src/dietlibc-0.34/lib/islower.o \
./src/dietlibc-0.34/lib/isprint.o \
./src/dietlibc-0.34/lib/ispunct.o \
./src/dietlibc-0.34/lib/isspace.o \
./src/dietlibc-0.34/lib/isupper.o \
./src/dietlibc-0.34/lib/iswalnum.o \
./src/dietlibc-0.34/lib/iswalpha.o \
./src/dietlibc-0.34/lib/iswblank.o \
./src/dietlibc-0.34/lib/iswcntrl.o \
./src/dietlibc-0.34/lib/iswdigit.o \
./src/dietlibc-0.34/lib/iswgraph.o \
./src/dietlibc-0.34/lib/iswlower.o \
./src/dietlibc-0.34/lib/iswprint.o \
./src/dietlibc-0.34/lib/iswpunct.o \
./src/dietlibc-0.34/lib/iswspace.o \
./src/dietlibc-0.34/lib/iswupper.o \
./src/dietlibc-0.34/lib/iswxdigit.o \
./src/dietlibc-0.34/lib/isxdigit.o \
./src/dietlibc-0.34/lib/labs.o \
./src/dietlibc-0.34/lib/lc_ctype.o \
./src/dietlibc-0.34/lib/ldiv.o \
./src/dietlibc-0.34/lib/listen.o \
./src/dietlibc-0.34/lib/llabs.o \
./src/dietlibc-0.34/lib/lldiv.o \
./src/dietlibc-0.34/lib/lockf.o \
./src/dietlibc-0.34/lib/longjmp.o \
./src/dietlibc-0.34/lib/lseek64.o \
./src/dietlibc-0.34/lib/makecontext.o \
./src/dietlibc-0.34/lib/mblen.o \
./src/dietlibc-0.34/lib/mbrlen.o \
./src/dietlibc-0.34/lib/mbrtowc.o \
./src/dietlibc-0.34/lib/mbsinit.o \
./src/dietlibc-0.34/lib/mbsrtowcs.o \
./src/dietlibc-0.34/lib/mbstowcs.o \
./src/dietlibc-0.34/lib/mbtowc.o \
./src/dietlibc-0.34/lib/memccpy.o \
./src/dietlibc-0.34/lib/memchr.o \
./src/dietlibc-0.34/lib/memcmp.o \
./src/dietlibc-0.34/lib/memcpy.o \
./src/dietlibc-0.34/lib/memmem.o \
./src/dietlibc-0.34/lib/memmove.o \
./src/dietlibc-0.34/lib/memrchr.o \
./src/dietlibc-0.34/lib/memset.o \
./src/dietlibc-0.34/lib/mkfifo.o \
./src/dietlibc-0.34/lib/mmap64.o \
./src/dietlibc-0.34/lib/mq_getattr.o \
./src/dietlibc-0.34/lib/mq_receive.o \
./src/dietlibc-0.34/lib/mq_send.o \
./src/dietlibc-0.34/lib/msgctl.o \
./src/dietlibc-0.34/lib/msgget.o \
./src/dietlibc-0.34/lib/msgrcv.o \
./src/dietlibc-0.34/lib/msgsnd.o \
./src/dietlibc-0.34/lib/mtx_destroy.o \
./src/dietlibc-0.34/lib/mtx_init.o \
./src/dietlibc-0.34/lib/mtx_lock.o \
./src/dietlibc-0.34/lib/mtx_timedlock.o \
./src/dietlibc-0.34/lib/mtx_trylock.o \
./src/dietlibc-0.34/lib/mtx_unlock.o \
./src/dietlibc-0.34/lib/nice.o \
./src/dietlibc-0.34/lib/open64.o \
./src/dietlibc-0.34/lib/opendir.o \
./src/dietlibc-0.34/lib/perror.o \
./src/dietlibc-0.34/lib/posix_fallocate.o \
./src/dietlibc-0.34/lib/pread.o \
./src/dietlibc-0.34/lib/pselect.o \
./src/dietlibc-0.34/lib/putenv.o \
./src/dietlibc-0.34/lib/pwrite.o \
./src/dietlibc-0.34/lib/qsort.o \
./src/dietlibc-0.34/lib/raise.o \
./src/dietlibc-0.34/lib/rand.o \
./src/dietlibc-0.34/lib/rand48.o \
./src/dietlibc-0.34/lib/rand_r.o \
./src/dietlibc-0.34/lib/readdir.o \
./src/dietlibc-0.34/lib/readdir64.o \
./src/dietlibc-0.34/lib/readdir_r.o \
./src/dietlibc-0.34/lib/reallocarray.o \
./src/dietlibc-0.34/lib/reboot.o \
./src/dietlibc-0.34/lib/recv.o \
./src/dietlibc-0.34/lib/recvfrom.o \
./src/dietlibc-0.34/lib/recvmsg.o \
./src/dietlibc-0.34/lib/remove.o \
./src/dietlibc-0.34/lib/rewind.o \
./src/dietlibc-0.34/lib/rewinddir.o \
./src/dietlibc-0.34/lib/sbrk.o \
./src/dietlibc-0.34/lib/secure_getenv.o \
./src/dietlibc-0.34/lib/seekdir.o \
./src/dietlibc-0.34/lib/semctl.o \
./src/dietlibc-0.34/lib/semget.o \
./src/dietlibc-0.34/lib/semop.o \
./src/dietlibc-0.34/lib/send.o \
./src/dietlibc-0.34/lib/sendmsg.o \
./src/dietlibc-0.34/lib/sendto.o \
./src/dietlibc-0.34/lib/setlinebuf.o \
./src/dietlibc-0.34/lib/setpgrp.o \
./src/dietlibc-0.34/lib/setsockopt.o \
./src/dietlibc-0.34/lib/shmat.o \
./src/dietlibc-0.34/lib/shmctl.o \
./src/dietlibc-0.34/lib/shmdt.o \
./src/dietlibc-0.34/lib/shmget.o \
./src/dietlibc-0.34/lib/shutdown.o \
./src/dietlibc-0.34/lib/sigaction.o \
./src/dietlibc-0.34/lib/sigaddset.o \
./src/dietlibc-0.34/lib/sigandset.o \
./src/dietlibc-0.34/lib/sigdelset.o \
./src/dietlibc-0.34/lib/sigemptyset.o \
./src/dietlibc-0.34/lib/sigfillset.o \
./src/dietlibc-0.34/lib/siginterrupt.o \
./src/dietlibc-0.34/lib/sigisemptyset.o \
./src/dietlibc-0.34/lib/sigismember.o \
./src/dietlibc-0.34/lib/sigjmp.o \
./src/dietlibc-0.34/lib/signal.o \
./src/dietlibc-0.34/lib/signalfd.o \
./src/dietlibc-0.34/lib/sigorset.o \
./src/dietlibc-0.34/lib/sigpending.o \
./src/dietlibc-0.34/lib/sigprocmask.o \
./src/dietlibc-0.34/lib/sigqueueinfo.o \
./src/dietlibc-0.34/lib/sigsuspend.o \
./src/dietlibc-0.34/lib/sigtimedwait.o \
./src/dietlibc-0.34/lib/sigwait.o \
./src/dietlibc-0.34/lib/siphash24.o \
./src/dietlibc-0.34/lib/sleep.o \
./src/dietlibc-0.34/lib/snprintf.o \
./src/dietlibc-0.34/lib/socket.o \
./src/dietlibc-0.34/lib/socketpair.o \
./src/dietlibc-0.34/lib/sprintf.o \
./src/dietlibc-0.34/lib/sscanf.o \
./src/dietlibc-0.34/lib/stack_smash_handler.o \
./src/dietlibc-0.34/lib/stack_smash_handler2.o \
./src/dietlibc-0.34/lib/stack_smash_handler3.o \
./src/dietlibc-0.34/lib/statfs64_cvt.o \
./src/dietlibc-0.34/lib/statvfs.o \
./src/dietlibc-0.34/lib/statvfs_cvt.o \
./src/dietlibc-0.34/lib/stpcpy.o \
./src/dietlibc-0.34/lib/stpncpy.o \
./src/dietlibc-0.34/lib/strcasecmp.o \
./src/dietlibc-0.34/lib/strcat.o \
./src/dietlibc-0.34/lib/strchr.o \
./src/dietlibc-0.34/lib/strcmp.o \
./src/dietlibc-0.34/lib/strcpy.o \
./src/dietlibc-0.34/lib/strcspn.o \
./src/dietlibc-0.34/lib/strdup.o \
./src/dietlibc-0.34/lib/strerror.o \
./src/dietlibc-0.34/lib/strlcat.o \
./src/dietlibc-0.34/lib/strlcpy.o \
./src/dietlibc-0.34/lib/strlen.o \
./src/dietlibc-0.34/lib/strncasecmp.o \
./src/dietlibc-0.34/lib/strncat.o \
./src/dietlibc-0.34/lib/strncmp.o \
./src/dietlibc-0.34/lib/strncpy.o \
./src/dietlibc-0.34/lib/strnlen.o \
./src/dietlibc-0.34/lib/strpbrk.o \
./src/dietlibc-0.34/lib/strrchr.o \
./src/dietlibc-0.34/lib/strsep.o \
./src/dietlibc-0.34/lib/strspn.o \
./src/dietlibc-0.34/lib/strstr.o \
./src/dietlibc-0.34/lib/strtod.o \
./src/dietlibc-0.34/lib/strtof.o \
./src/dietlibc-0.34/lib/strtok.o \
./src/dietlibc-0.34/lib/strtok_r.o \
./src/dietlibc-0.34/lib/strtol.o \
./src/dietlibc-0.34/lib/strtold.o \
./src/dietlibc-0.34/lib/strtoll.o \
./src/dietlibc-0.34/lib/strtoul.o \
./src/dietlibc-0.34/lib/strtoull.o \
./src/dietlibc-0.34/lib/strverscmp.o \
./src/dietlibc-0.34/lib/strxfrm.o \
./src/dietlibc-0.34/lib/swab.o \
./src/dietlibc-0.34/lib/swapcontext.o \
./src/dietlibc-0.34/lib/sys_siglist.o \
./src/dietlibc-0.34/lib/tcdrain.o \
./src/dietlibc-0.34/lib/tcflow.o \
./src/dietlibc-0.34/lib/tcflush.o \
./src/dietlibc-0.34/lib/tcgetattr.o \
./src/dietlibc-0.34/lib/tcgetpgrp.o \
./src/dietlibc-0.34/lib/tcgetsid.o \
./src/dietlibc-0.34/lib/tcsendbreak.o \
./src/dietlibc-0.34/lib/tcsetattr.o \
./src/dietlibc-0.34/lib/tcsetpgrp.o \
./src/dietlibc-0.34/lib/telldir.o \
./src/dietlibc-0.34/lib/thrd_create.o \
./src/dietlibc-0.34/lib/thrd_current.o \
./src/dietlibc-0.34/lib/thrd_detach.o \
./src/dietlibc-0.34/lib/thrd_exit.o \
./src/dietlibc-0.34/lib/thrd_join.o \
./src/dietlibc-0.34/lib/thrd_root.o \
./src/dietlibc-0.34/lib/timerfd_create.o \
./src/dietlibc-0.34/lib/timingsafe_bcmp.o \
./src/dietlibc-0.34/lib/timingsafe_memcmp.o \
./src/dietlibc-0.34/lib/tolower.o \
./src/dietlibc-0.34/lib/toupper.o \
./src/dietlibc-0.34/lib/towlower.o \
./src/dietlibc-0.34/lib/towupper.o \
./src/dietlibc-0.34/lib/tss_create.o \
./src/dietlibc-0.34/lib/tss_delete.o \
./src/dietlibc-0.34/lib/tss_get.o \
./src/dietlibc-0.34/lib/tss_set.o \
./src/dietlibc-0.34/lib/ttyname.o \
./src/dietlibc-0.34/lib/usleep.o \
./src/dietlibc-0.34/lib/vdso_dlsym.o \
./src/dietlibc-0.34/lib/vfork.o \
./src/dietlibc-0.34/lib/vsnprintf.o \
./src/dietlibc-0.34/lib/vsprintf.o \
./src/dietlibc-0.34/lib/vsscanf.o \
./src/dietlibc-0.34/lib/wait.o \
./src/dietlibc-0.34/lib/wait3.o \
./src/dietlibc-0.34/lib/wcrtomb.o \
./src/dietlibc-0.34/lib/wcscat.o \
./src/dietlibc-0.34/lib/wcschr.o \
./src/dietlibc-0.34/lib/wcscmp.o \
./src/dietlibc-0.34/lib/wcscpy.o \
./src/dietlibc-0.34/lib/wcslen.o \
./src/dietlibc-0.34/lib/wcsncat.o \
./src/dietlibc-0.34/lib/wcsncmp.o \
./src/dietlibc-0.34/lib/wcsncpy.o \
./src/dietlibc-0.34/lib/wcsrchr.o \
./src/dietlibc-0.34/lib/wcsrtombs.o \
./src/dietlibc-0.34/lib/wcsstr.o \
./src/dietlibc-0.34/lib/wcstombs.o \
./src/dietlibc-0.34/lib/wcswidth.o \
./src/dietlibc-0.34/lib/wctomb.o \
./src/dietlibc-0.34/lib/wcwidth.o \
./src/dietlibc-0.34/lib/write12.o 

C_DEPS += \
./src/dietlibc-0.34/lib/__alarm.d \
./src/dietlibc-0.34/lib/__dtostr.d \
./src/dietlibc-0.34/lib/__fcntl64.d \
./src/dietlibc-0.34/lib/__finite.d \
./src/dietlibc-0.34/lib/__fstat64.d \
./src/dietlibc-0.34/lib/__fstatat64.d \
./src/dietlibc-0.34/lib/__fstatfs64.d \
./src/dietlibc-0.34/lib/__ftruncate64.d \
./src/dietlibc-0.34/lib/__get_cur_tcb.d \
./src/dietlibc-0.34/lib/__getcwd.d \
./src/dietlibc-0.34/lib/__inotify_init.d \
./src/dietlibc-0.34/lib/__isinf.d \
./src/dietlibc-0.34/lib/__isnan.d \
./src/dietlibc-0.34/lib/__lstat64.d \
./src/dietlibc-0.34/lib/__ltostr.d \
./src/dietlibc-0.34/lib/__mmap.d \
./src/dietlibc-0.34/lib/__ptrace.d \
./src/dietlibc-0.34/lib/__sched_getaffinity.d \
./src/dietlibc-0.34/lib/__sendfile64.d \
./src/dietlibc-0.34/lib/__stat64.d \
./src/dietlibc-0.34/lib/__stat64_cvt.d \
./src/dietlibc-0.34/lib/__statfs64.d \
./src/dietlibc-0.34/lib/__stime.d \
./src/dietlibc-0.34/lib/__sysctl.d \
./src/dietlibc-0.34/lib/__time.d \
./src/dietlibc-0.34/lib/__truncate64.d \
./src/dietlibc-0.34/lib/__umount.d \
./src/dietlibc-0.34/lib/__utime.d \
./src/dietlibc-0.34/lib/__v_printf.d \
./src/dietlibc-0.34/lib/__v_scanf.d \
./src/dietlibc-0.34/lib/_brk.d \
./src/dietlibc-0.34/lib/_getpriority.d \
./src/dietlibc-0.34/lib/abort.d \
./src/dietlibc-0.34/lib/abs.d \
./src/dietlibc-0.34/lib/accept.d \
./src/dietlibc-0.34/lib/adjtime.d \
./src/dietlibc-0.34/lib/alloc.d \
./src/dietlibc-0.34/lib/arc4random.d \
./src/dietlibc-0.34/lib/assert_fail.d \
./src/dietlibc-0.34/lib/atexit.d \
./src/dietlibc-0.34/lib/atof.d \
./src/dietlibc-0.34/lib/atoi.d \
./src/dietlibc-0.34/lib/atol.d \
./src/dietlibc-0.34/lib/atoll.d \
./src/dietlibc-0.34/lib/bind.d \
./src/dietlibc-0.34/lib/binshstr.d \
./src/dietlibc-0.34/lib/bsearch.d \
./src/dietlibc-0.34/lib/btowc.d \
./src/dietlibc-0.34/lib/call_once.d \
./src/dietlibc-0.34/lib/cfgetospeed.d \
./src/dietlibc-0.34/lib/cfmakeraw.d \
./src/dietlibc-0.34/lib/cfsetispeed.d \
./src/dietlibc-0.34/lib/cfsetospeed.d \
./src/dietlibc-0.34/lib/closedir.d \
./src/dietlibc-0.34/lib/cnd_broadcast.d \
./src/dietlibc-0.34/lib/cnd_destroy.d \
./src/dietlibc-0.34/lib/cnd_init.d \
./src/dietlibc-0.34/lib/cnd_signal.d \
./src/dietlibc-0.34/lib/cnd_timedwait.d \
./src/dietlibc-0.34/lib/cnd_wait.d \
./src/dietlibc-0.34/lib/connect.d \
./src/dietlibc-0.34/lib/creat.d \
./src/dietlibc-0.34/lib/creat64.d \
./src/dietlibc-0.34/lib/div.d \
./src/dietlibc-0.34/lib/errlistu.d \
./src/dietlibc-0.34/lib/errno.d \
./src/dietlibc-0.34/lib/errno_location.d \
./src/dietlibc-0.34/lib/eventfd.d \
./src/dietlibc-0.34/lib/exec_lib.d \
./src/dietlibc-0.34/lib/execl.d \
./src/dietlibc-0.34/lib/execle.d \
./src/dietlibc-0.34/lib/execlp.d \
./src/dietlibc-0.34/lib/execv.d \
./src/dietlibc-0.34/lib/execvp.d \
./src/dietlibc-0.34/lib/explicit_bzero.d \
./src/dietlibc-0.34/lib/fdopendir.d \
./src/dietlibc-0.34/lib/ffs.d \
./src/dietlibc-0.34/lib/fstatvfs.d \
./src/dietlibc-0.34/lib/ftw.d \
./src/dietlibc-0.34/lib/ftw64.d \
./src/dietlibc-0.34/lib/getdomainname.d \
./src/dietlibc-0.34/lib/getentropy.d \
./src/dietlibc-0.34/lib/getenv.d \
./src/dietlibc-0.34/lib/gethostname.d \
./src/dietlibc-0.34/lib/getopt.d \
./src/dietlibc-0.34/lib/getpeername.d \
./src/dietlibc-0.34/lib/getpgrp.d \
./src/dietlibc-0.34/lib/getsockname.d \
./src/dietlibc-0.34/lib/getsockopt.d \
./src/dietlibc-0.34/lib/hcreate.d \
./src/dietlibc-0.34/lib/hcreate_r.d \
./src/dietlibc-0.34/lib/hdestroy_r.d \
./src/dietlibc-0.34/lib/hsearch_r.d \
./src/dietlibc-0.34/lib/htonl.d \
./src/dietlibc-0.34/lib/htons.d \
./src/dietlibc-0.34/lib/if_freenameindex.d \
./src/dietlibc-0.34/lib/if_indextoname.d \
./src/dietlibc-0.34/lib/if_nameindex.d \
./src/dietlibc-0.34/lib/if_nametoindex.d \
./src/dietlibc-0.34/lib/ipv6constants.d \
./src/dietlibc-0.34/lib/isalnum.d \
./src/dietlibc-0.34/lib/isalpha.d \
./src/dietlibc-0.34/lib/isascii.d \
./src/dietlibc-0.34/lib/isatty.d \
./src/dietlibc-0.34/lib/isblank.d \
./src/dietlibc-0.34/lib/iscntrl.d \
./src/dietlibc-0.34/lib/isdigit.d \
./src/dietlibc-0.34/lib/isgraph.d \
./src/dietlibc-0.34/lib/islower.d \
./src/dietlibc-0.34/lib/isprint.d \
./src/dietlibc-0.34/lib/ispunct.d \
./src/dietlibc-0.34/lib/isspace.d \
./src/dietlibc-0.34/lib/isupper.d \
./src/dietlibc-0.34/lib/iswalnum.d \
./src/dietlibc-0.34/lib/iswalpha.d \
./src/dietlibc-0.34/lib/iswblank.d \
./src/dietlibc-0.34/lib/iswcntrl.d \
./src/dietlibc-0.34/lib/iswdigit.d \
./src/dietlibc-0.34/lib/iswgraph.d \
./src/dietlibc-0.34/lib/iswlower.d \
./src/dietlibc-0.34/lib/iswprint.d \
./src/dietlibc-0.34/lib/iswpunct.d \
./src/dietlibc-0.34/lib/iswspace.d \
./src/dietlibc-0.34/lib/iswupper.d \
./src/dietlibc-0.34/lib/iswxdigit.d \
./src/dietlibc-0.34/lib/isxdigit.d \
./src/dietlibc-0.34/lib/labs.d \
./src/dietlibc-0.34/lib/lc_ctype.d \
./src/dietlibc-0.34/lib/ldiv.d \
./src/dietlibc-0.34/lib/listen.d \
./src/dietlibc-0.34/lib/llabs.d \
./src/dietlibc-0.34/lib/lldiv.d \
./src/dietlibc-0.34/lib/lockf.d \
./src/dietlibc-0.34/lib/longjmp.d \
./src/dietlibc-0.34/lib/lseek64.d \
./src/dietlibc-0.34/lib/makecontext.d \
./src/dietlibc-0.34/lib/mblen.d \
./src/dietlibc-0.34/lib/mbrlen.d \
./src/dietlibc-0.34/lib/mbrtowc.d \
./src/dietlibc-0.34/lib/mbsinit.d \
./src/dietlibc-0.34/lib/mbsrtowcs.d \
./src/dietlibc-0.34/lib/mbstowcs.d \
./src/dietlibc-0.34/lib/mbtowc.d \
./src/dietlibc-0.34/lib/memccpy.d \
./src/dietlibc-0.34/lib/memchr.d \
./src/dietlibc-0.34/lib/memcmp.d \
./src/dietlibc-0.34/lib/memcpy.d \
./src/dietlibc-0.34/lib/memmem.d \
./src/dietlibc-0.34/lib/memmove.d \
./src/dietlibc-0.34/lib/memrchr.d \
./src/dietlibc-0.34/lib/memset.d \
./src/dietlibc-0.34/lib/mkfifo.d \
./src/dietlibc-0.34/lib/mmap64.d \
./src/dietlibc-0.34/lib/mq_getattr.d \
./src/dietlibc-0.34/lib/mq_receive.d \
./src/dietlibc-0.34/lib/mq_send.d \
./src/dietlibc-0.34/lib/msgctl.d \
./src/dietlibc-0.34/lib/msgget.d \
./src/dietlibc-0.34/lib/msgrcv.d \
./src/dietlibc-0.34/lib/msgsnd.d \
./src/dietlibc-0.34/lib/mtx_destroy.d \
./src/dietlibc-0.34/lib/mtx_init.d \
./src/dietlibc-0.34/lib/mtx_lock.d \
./src/dietlibc-0.34/lib/mtx_timedlock.d \
./src/dietlibc-0.34/lib/mtx_trylock.d \
./src/dietlibc-0.34/lib/mtx_unlock.d \
./src/dietlibc-0.34/lib/nice.d \
./src/dietlibc-0.34/lib/open64.d \
./src/dietlibc-0.34/lib/opendir.d \
./src/dietlibc-0.34/lib/perror.d \
./src/dietlibc-0.34/lib/posix_fallocate.d \
./src/dietlibc-0.34/lib/pread.d \
./src/dietlibc-0.34/lib/pselect.d \
./src/dietlibc-0.34/lib/putenv.d \
./src/dietlibc-0.34/lib/pwrite.d \
./src/dietlibc-0.34/lib/qsort.d \
./src/dietlibc-0.34/lib/raise.d \
./src/dietlibc-0.34/lib/rand.d \
./src/dietlibc-0.34/lib/rand48.d \
./src/dietlibc-0.34/lib/rand_r.d \
./src/dietlibc-0.34/lib/readdir.d \
./src/dietlibc-0.34/lib/readdir64.d \
./src/dietlibc-0.34/lib/readdir_r.d \
./src/dietlibc-0.34/lib/reallocarray.d \
./src/dietlibc-0.34/lib/reboot.d \
./src/dietlibc-0.34/lib/recv.d \
./src/dietlibc-0.34/lib/recvfrom.d \
./src/dietlibc-0.34/lib/recvmsg.d \
./src/dietlibc-0.34/lib/remove.d \
./src/dietlibc-0.34/lib/rewind.d \
./src/dietlibc-0.34/lib/rewinddir.d \
./src/dietlibc-0.34/lib/sbrk.d \
./src/dietlibc-0.34/lib/secure_getenv.d \
./src/dietlibc-0.34/lib/seekdir.d \
./src/dietlibc-0.34/lib/semctl.d \
./src/dietlibc-0.34/lib/semget.d \
./src/dietlibc-0.34/lib/semop.d \
./src/dietlibc-0.34/lib/send.d \
./src/dietlibc-0.34/lib/sendmsg.d \
./src/dietlibc-0.34/lib/sendto.d \
./src/dietlibc-0.34/lib/setlinebuf.d \
./src/dietlibc-0.34/lib/setpgrp.d \
./src/dietlibc-0.34/lib/setsockopt.d \
./src/dietlibc-0.34/lib/shmat.d \
./src/dietlibc-0.34/lib/shmctl.d \
./src/dietlibc-0.34/lib/shmdt.d \
./src/dietlibc-0.34/lib/shmget.d \
./src/dietlibc-0.34/lib/shutdown.d \
./src/dietlibc-0.34/lib/sigaction.d \
./src/dietlibc-0.34/lib/sigaddset.d \
./src/dietlibc-0.34/lib/sigandset.d \
./src/dietlibc-0.34/lib/sigdelset.d \
./src/dietlibc-0.34/lib/sigemptyset.d \
./src/dietlibc-0.34/lib/sigfillset.d \
./src/dietlibc-0.34/lib/siginterrupt.d \
./src/dietlibc-0.34/lib/sigisemptyset.d \
./src/dietlibc-0.34/lib/sigismember.d \
./src/dietlibc-0.34/lib/sigjmp.d \
./src/dietlibc-0.34/lib/signal.d \
./src/dietlibc-0.34/lib/signalfd.d \
./src/dietlibc-0.34/lib/sigorset.d \
./src/dietlibc-0.34/lib/sigpending.d \
./src/dietlibc-0.34/lib/sigprocmask.d \
./src/dietlibc-0.34/lib/sigqueueinfo.d \
./src/dietlibc-0.34/lib/sigsuspend.d \
./src/dietlibc-0.34/lib/sigtimedwait.d \
./src/dietlibc-0.34/lib/sigwait.d \
./src/dietlibc-0.34/lib/siphash24.d \
./src/dietlibc-0.34/lib/sleep.d \
./src/dietlibc-0.34/lib/snprintf.d \
./src/dietlibc-0.34/lib/socket.d \
./src/dietlibc-0.34/lib/socketpair.d \
./src/dietlibc-0.34/lib/sprintf.d \
./src/dietlibc-0.34/lib/sscanf.d \
./src/dietlibc-0.34/lib/stack_smash_handler.d \
./src/dietlibc-0.34/lib/stack_smash_handler2.d \
./src/dietlibc-0.34/lib/stack_smash_handler3.d \
./src/dietlibc-0.34/lib/statfs64_cvt.d \
./src/dietlibc-0.34/lib/statvfs.d \
./src/dietlibc-0.34/lib/statvfs_cvt.d \
./src/dietlibc-0.34/lib/stpcpy.d \
./src/dietlibc-0.34/lib/stpncpy.d \
./src/dietlibc-0.34/lib/strcasecmp.d \
./src/dietlibc-0.34/lib/strcat.d \
./src/dietlibc-0.34/lib/strchr.d \
./src/dietlibc-0.34/lib/strcmp.d \
./src/dietlibc-0.34/lib/strcpy.d \
./src/dietlibc-0.34/lib/strcspn.d \
./src/dietlibc-0.34/lib/strdup.d \
./src/dietlibc-0.34/lib/strerror.d \
./src/dietlibc-0.34/lib/strlcat.d \
./src/dietlibc-0.34/lib/strlcpy.d \
./src/dietlibc-0.34/lib/strlen.d \
./src/dietlibc-0.34/lib/strncasecmp.d \
./src/dietlibc-0.34/lib/strncat.d \
./src/dietlibc-0.34/lib/strncmp.d \
./src/dietlibc-0.34/lib/strncpy.d \
./src/dietlibc-0.34/lib/strnlen.d \
./src/dietlibc-0.34/lib/strpbrk.d \
./src/dietlibc-0.34/lib/strrchr.d \
./src/dietlibc-0.34/lib/strsep.d \
./src/dietlibc-0.34/lib/strspn.d \
./src/dietlibc-0.34/lib/strstr.d \
./src/dietlibc-0.34/lib/strtod.d \
./src/dietlibc-0.34/lib/strtof.d \
./src/dietlibc-0.34/lib/strtok.d \
./src/dietlibc-0.34/lib/strtok_r.d \
./src/dietlibc-0.34/lib/strtol.d \
./src/dietlibc-0.34/lib/strtold.d \
./src/dietlibc-0.34/lib/strtoll.d \
./src/dietlibc-0.34/lib/strtoul.d \
./src/dietlibc-0.34/lib/strtoull.d \
./src/dietlibc-0.34/lib/strverscmp.d \
./src/dietlibc-0.34/lib/strxfrm.d \
./src/dietlibc-0.34/lib/swab.d \
./src/dietlibc-0.34/lib/swapcontext.d \
./src/dietlibc-0.34/lib/sys_siglist.d \
./src/dietlibc-0.34/lib/tcdrain.d \
./src/dietlibc-0.34/lib/tcflow.d \
./src/dietlibc-0.34/lib/tcflush.d \
./src/dietlibc-0.34/lib/tcgetattr.d \
./src/dietlibc-0.34/lib/tcgetpgrp.d \
./src/dietlibc-0.34/lib/tcgetsid.d \
./src/dietlibc-0.34/lib/tcsendbreak.d \
./src/dietlibc-0.34/lib/tcsetattr.d \
./src/dietlibc-0.34/lib/tcsetpgrp.d \
./src/dietlibc-0.34/lib/telldir.d \
./src/dietlibc-0.34/lib/thrd_create.d \
./src/dietlibc-0.34/lib/thrd_current.d \
./src/dietlibc-0.34/lib/thrd_detach.d \
./src/dietlibc-0.34/lib/thrd_exit.d \
./src/dietlibc-0.34/lib/thrd_join.d \
./src/dietlibc-0.34/lib/thrd_root.d \
./src/dietlibc-0.34/lib/timerfd_create.d \
./src/dietlibc-0.34/lib/timingsafe_bcmp.d \
./src/dietlibc-0.34/lib/timingsafe_memcmp.d \
./src/dietlibc-0.34/lib/tolower.d \
./src/dietlibc-0.34/lib/toupper.d \
./src/dietlibc-0.34/lib/towlower.d \
./src/dietlibc-0.34/lib/towupper.d \
./src/dietlibc-0.34/lib/tss_create.d \
./src/dietlibc-0.34/lib/tss_delete.d \
./src/dietlibc-0.34/lib/tss_get.d \
./src/dietlibc-0.34/lib/tss_set.d \
./src/dietlibc-0.34/lib/ttyname.d \
./src/dietlibc-0.34/lib/usleep.d \
./src/dietlibc-0.34/lib/vdso_dlsym.d \
./src/dietlibc-0.34/lib/vfork.d \
./src/dietlibc-0.34/lib/vsnprintf.d \
./src/dietlibc-0.34/lib/vsprintf.d \
./src/dietlibc-0.34/lib/vsscanf.d \
./src/dietlibc-0.34/lib/wait.d \
./src/dietlibc-0.34/lib/wait3.d \
./src/dietlibc-0.34/lib/wcrtomb.d \
./src/dietlibc-0.34/lib/wcscat.d \
./src/dietlibc-0.34/lib/wcschr.d \
./src/dietlibc-0.34/lib/wcscmp.d \
./src/dietlibc-0.34/lib/wcscpy.d \
./src/dietlibc-0.34/lib/wcslen.d \
./src/dietlibc-0.34/lib/wcsncat.d \
./src/dietlibc-0.34/lib/wcsncmp.d \
./src/dietlibc-0.34/lib/wcsncpy.d \
./src/dietlibc-0.34/lib/wcsrchr.d \
./src/dietlibc-0.34/lib/wcsrtombs.d \
./src/dietlibc-0.34/lib/wcsstr.d \
./src/dietlibc-0.34/lib/wcstombs.d \
./src/dietlibc-0.34/lib/wcswidth.d \
./src/dietlibc-0.34/lib/wctomb.d \
./src/dietlibc-0.34/lib/wcwidth.d \
./src/dietlibc-0.34/lib/write12.d 


# Each subdirectory must supply rules for building sources it contributes
src/dietlibc-0.34/lib/%.o: ../src/dietlibc-0.34/lib/%.c src/dietlibc-0.34/lib/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Arm Cross C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m3 -mthumb -mthumb-interwork -O0 -ffunction-sections -fdata-sections -fno-builtin -fPIC -n -pie -fpie -fPIC -fpic -msingle-pic-base -mno-pic-data-is-text-relative -Wall  -g -D__dietlibc__ -D__arm__ -I"D:\Project\MyProject1\mkrtos_real\mkrtos_ym\src\dietlibc-0.34" -I"D:\Project\MyProject1\mkrtos_real\mkrtos_ym\src\dietlibc-0.34\include" -I"D:\Project\MyProject1\mkrtos_real\mkrtos_ym\src" -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


